### ISSUE TITLE
Q: fake-log process and duplicates in diff files

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osmdbt#11]
osmdbt-fake-log may already be the solution for https://github.com/zerebubuth/osm-logical/issues/2, which is good news. 

I have a question on how the overall process looks like:

1. Normal replication breaks down

some time later:

2. Operator re-establishes logical replication on the database without calling any of the osmdbt-tools, except for enable/disable-replication maybe?

3. Operator runs osmdbt-fake-log
As the last .osc.gz file might still have some in-flight transactions, I cannot simply use the latest timestamp I find in that osc file, but need to go back some time (a few minutes) into the past. Otherwise, there's a risk that I might miss some object versions. Although that risk has greatly reduced since about a year, it's not zero.
(that's the old discussion about time based vs. transaction based replication -> [wiki](https://wiki.openstreetmap.org/wiki/Osmosis/Replication#Time-aligned_versus_Transaction-aligned))

4. Operator continues with normal osmdbt-get-log and *-create-diff?

I'm not exactly sure how a smooth transition from logical replication to fake-log and back to logical replication looks like. In particular, I'm a bit worried that the diff files may include the same object version multiple times across different osc files, or that there might be even some going back and forth between object versions of the same object.

Somehow I was expecting to see a comparison between the existing osc files and objects to be written in new osc files, as part of the fake-log recovery process, to filter out any anomalies.

As @zerebubuth noted in https://github.com/openstreetmap/operations/issues/154#issuecomment-633975216, transitioning from the old to the new replication may have similar requirements.

**Comment by zerebubuth** [comment]
I was hoping to make this as robust as possible, because any "operator does X" is highly likely to fail due to human error. The likelihood of error increases with the rarity of the event. I've personally caused errors when SSHing into servers from my phone because a rare failure happened and I thought it needed to be fixed more urgently than I'd be able to find a laptop or desktop.

Therefore, I would suggest that the process be designed so that `osmdbt-fake-log` is not used at all during the most common kinds of replication breakdown (machine crashes, reboots, software updates, etc...). This should be possible, given careful attention to the order of events.

However, it should also be noted that _exactly once_ delivery is essentially impossible, and given the choice between _at least once_ and _at most once_, we're going with _at least once_. Between this, the inevitable bugs and operator errors: Downstream consumers of diffs should understand that (very rare) duplicates are possible and, if it matters to their use-case, be robust to them.

**Comment by mmd-osm** [comment]
@zerebubuth : https://github.com/openstreetmap/osmdbt#1-catch-up-old-log-files already covers a lot of those "normal" system crash scenarios. My impression is that this list should have a fairly good coverage of what can go wrong.

Maybe I should rephrase my first point to "Logical replication is not working at all while data is flowing in", and we need to re-establish that process. I know this might be pretty rare, but as long as this isn't in production yet, there's still time to sketch some ideas.

**Comment by joto** [comment]
I think we thought through most of the problems we can anticipate and the software that's needed is in place. I understand the argument from @zerebubuth that recovery should ba as automatic as possible so that a sysadmin can't break anything when under high stress. On the other hand writing software for cases that might never happen and are essentially impossible to test for is also very difficult. It is more important the sysadmins can understand what's going on instead of having some clever software that might or might not work correctly when the time comes.

> Somehow I was expecting to see a comparison between the existing osc files and objects to be written in new osc files, as part of the fake-log recovery process, to filter out any anomalies.

In my opinion this is far too difficult to do in an automated fashion, you'd still need a person to look at this.

And, as @zerebubuth mentioned, the best we can do is *at least once delivery*. We are not shooting people to the moon here, so at some point we just have to say its good enough.

**Comment by zerebubuth** [comment]
> It is more important the sysadmins can understand what's going on instead of having some clever software that might or might not work correctly when the time comes.

I completely agree! The ideal would be something that's simple and easy to understand (i.e: no clever magic), _and_ also robust and self-repairing. These goals aren't impossible to achieve together, although discovering the right abstractions can be a challenge!

> In my opinion this is far too difficult to do in an automated fashion, you'd still need a person to look at this.

I think the classes of errors fall into two categories:

1. The system crashed / rebooted, but the database is still intact (i.e: the replication slot exists) and the disk is intact (i.e: valid, but might be missing unsynced writes). In this situation I think we should aim to recover without operator input.
2. The system is broken; database corruption, replication slot missing, files on disk are filled with random noise, etc... In this situation the best we can do is exit with a big error message. Anything the program does is more likely to make things worse than better and a human will have to decide whether (and how) to fix it, or to restore from backup.

@mmd-osm wrote:
> Maybe I should rephrase my first point to "Logical replication is not working at all while data is flowing in", and we need to re-establish that process.

I like the idea, but I worry that the implementation might be much more complex than the description. It seems like you're describing a transaction that spans the API, through the database and all the way to the replication diffs - such that if a replication diff fails to commit, the API would return an error message. Indeed, PostgreSQL already has something similar with synchronous replication (anything committed on the primary is guaranteed to be safe on-disk on the replica(s) before `commit` returns).

Unfortunately, the more systems that _all_ have to be operating correctly at the same time, the lower the availability of the whole system. This limits the scope for operations such as rebooting a replica - if it's the only one, it takes down the whole system. I think it's probably better for a human to make decisions about whether/how much to degrade the API when a failure or planned maintenance happens.

**Comment by mmd-osm** [comment]
Thanks everyone for your thoughts and insights on this topic. I do realize that a fully automated recovery process using fake-log is probably not feasible (which is ok). Maybe there's some time once the test system is up and running for the sysadmins to try out the fake-log process.

@zerebubuth : I came across this blog post, and don't know exactly if this would also affect us in a failover scenario (where fake-log might also come in handy): https://www.percona.com/blog/2020/05/21/failover-of-logical-replication-slots-in-postgresql/

**Comment by joto** [comment]
I believe there are no actionable things in this issue here. This will just be part of testing and, possibly, documentation if we find that it isn't clear. Closing here.
