### ISSUE TITLE
state.txt timestamp - and osmosis compatibility

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osmdbt#26]
Caveat: this topic is somewhat involved, and I've only started to realize that more research about the old osmosis logic is needed here to stay compatible with the old logic. 

I've noticed that osmdbt uses a different approach to determine the timestamp for a new state.txt file (see create_replication_log_name: `osmium::Timestamp now{time};`) compared to the previous osmosis implementation.

Previously, state.txt would print the current timestamp when the process was executed as comment in the very first line.

To highlight the difference in both values, I'm using the example from the July 5 9-hours outage again, and show both the actual execution time (as column "comment in header") and the `timestamp` field.

As you can see in the following table, `timestamp=` matches the actual object timestamps contained in a minutely diff file, rather than the execution time. The timestamp continues to grow in roughly 30 minutes steps, which matches the maximum number of changes per osmosis run at that time.

File | comment in header | timestamp 
-----------|---------------|--------------|
https://planet.openstreetmap.org/replication/minute/004/095/148.state.txt | #Sun Jul 05 16:17:14 UTC 2020 | 2020-07-05T09\:54\:46Z
https://planet.openstreetmap.org/replication/minute/004/095/149.state.txt | #Sun Jul 05 16:18:10 UTC 2020 | 2020-07-05T10\:19\:44Z
https://planet.openstreetmap.org/replication/minute/004/095/150.state.txt | #Sun Jul 05 16:19:12 UTC 2020 | 2020-07-05T10\:46\:31Z

The actual logic that is used by osmosis is much more involved, and can basically be found in https://github.com/openstreetmap/osmosis/blob/master/osmosis-apidb/src/main/java/org/openstreetmap/osmosis/apidb/v0_6/impl/Replicator.java

It provides some clues about the timestamp field, such as:

> A key rule in replication is that the timestamp we specify in our replication state is always equal to or later than all data timestamps. This allows consumers to know that when they pick a timestamp to start replicating from that *all* data created after that timestamp will be included in subsequent replications.

For sure, this is only the tip of the iceberg, and as stated initially, more research is needed.

## Origin of timestamp information

Interesting point that I've seen is that osmosis doesn't trust the local system to provide the correct timestamp, and resorts to an SQL query instead: https://github.com/openstreetmap/osmosis/blob/master/osmosis-apidb/src/main/java/org/openstreetmap/osmosis/apidb/v0_6/impl/TimeDao.java#L37

That may not have the highest priority (due to NTP usage across servers), still I wanted to mention this peculiarity.

**Comment by joto** [comment]
I am a bit confused here. I don't care about the comment in the state.txt file, osmdbt doesn't even generate it. For the actual timestamp, I have to check where this comes from, I don't remember of the top of my head.

Concerning the origin of the timestamp information: Different clocks were historically a problem with OSM data. That's probably where this came from.

**Comment by joto** [comment]
I have looked into this some more and believe the comment you found in the Osmosis code isn't really that helpful. And the Osmosis code is overly complex.

The basic problem with replication in our case is this:

There can be multiple transactions open in the database at the same time with objects being written to the database with whatever timestamp is current at that point in time. When a transaction is committed, the objects show up in the log file, but there might be other transactions still open with objects with an unknown timestamp (which might be smaller or larger than any timestamp we have in the committed transaction). So we can not know whether there are unprocessed objects with older and/or newer timestamps than we currently have. So it might be that there are objects with timestamp `t` in change file 1234.osc.gz and in 1235.osc.gz there is an object with a timestamp `<t`. That's why we can't use the timestamps as some kind of marker for the replication, but we use the sequence numbers instead.

So it doesn't really matter all that much what exact timestamp is in the file. For an ongoing replication you simply keep incrementing the sequence number. When you set up a new replication you have to find out at what point in time you want to start the replication, then go back "a bit" and start from there. Usually you will start from a planet dump, but they use a separate mechanism that is not synced with the change files, so there is no clean way to start consuming change files exactly at that point where a planet dump is. So you go back "a bit" and hope that it all works out. We should document what this "a bit" is and tell users how to properly consume changes, but this isn't really a concern for us here.

I have just changed the code in 58513a54b0104979c3817073ddb434968cda2182 and put the largest timestamp of any of the objects in the .osc.gz file into the state.txt, because I believe that is probably the most useful timestamp here. It is arguably a bit more useful than the timestamp from the log file I had used before, because that doesn't really tell us anything about the data, just the random time when the transaction was closed.
